### ISSUE TITLE
Add PHP 7.4 compatibility

### ISSUE THREAD

**Issue by Morgy93** [elgentos/frontend2fa#10]
Hello,

currently there's no php7.4 compatibility:

```
- juashyam/authenticator 0.0.1 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0|~7.3.0 -> your php version (7.4.24) does not satisfy that requirement.
- elgentos/frontend2fa 0.1.10 requires juashyam/authenticator 0.0.1 -> satisfiable by juashyam/authenticator[0.0.1]
```

With Magento 2.4.4 there will be official PHP 8.1 support, so this should be considered as well.

**Comment by peterjaap** [comment]
I've removed the PHP version constrained and released a new version; https://github.com/elgentos/frontend2fa/releases/tag/0.1.11

However, this doesn't solve the issue because the underlying package `juashyam/authenticator` still restricts to PHP 7.3. You might have more luck opening an issie there; https://github.com/juashyam/2-Factor-Authentication

Closing this issue here.

**Comment by peterjaap** [comment]
Or maybe remove that dependency at all, see #1
