### ISSUE TITLE
Invalid barcode

### ISSUE THREAD

**Issue by melaxon** [elgentos/frontend2fa#5]
I cannot scan qr-code with google authenticator as it throws error message saying that the barcode is invalid and 'secret is not a token for authentication'

See screenshot here:
https://github.com/juashyam/2-Factor-Authentication/issues/7

**Comment by peterjaap** [comment]
@melaxon have you updated to the latest version? I had that issue too and fixed it in https://github.com/elgentos/frontend2fa/commit/892fe577f6b527f55826a062f3fd7924b46a1431

I'ts because Google Authenticator doesn't like spaces in the title.

Please note that this extension is not the same as juashyam/2-Factor-Authentication, it just uses that extension as a base.
